name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to GitHub Container Registry
        env:
          DOCKER_USERNAME: kawinz-org
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: echo $DOCKER_PASSWORD | docker login ghcr.io --username mommde --password-stdin

      - name: Build & Tag
        run: docker build -t ghcr.io/kawinz-org/imgmf-test-container-repository:latest -t ghcr.io/kawinz-org/imgmf-test-container-repository:"$GITHUB_SHA" ./docker-hello-world/

      - name: Push Image to GitHub Container Registry
        run: docker push ghcr.io/kawinz-org/imgmf-test-container-repository:latest

      - name: Push Specific Image to GitHub Container Registry
        run: docker push ghcr.io/kawinz-org/imgmf-test-container-repository:"$GITHUB_SHA"
