name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        env:
          DOCKER_USERNAME: kawinz-org
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: echo $DOCKER_PASSWORD | docker login ghcr.io --username kawinz-org --password-stdin
      
      - name: 
        run: ./hello-world/update.sh
      
